# Copyright 2019 The SEED Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG grpc_image
FROM $grpc_image as grpc

# Needed to disable interactive configuration by tzdata.
RUN ln -fs /usr/share/zoneinfo/Europe/Dublin /etc/localtime

RUN apt-get update && apt-get install -y \
  git \
  cmake \
  build-essential \
  libgl1-mesa-dev \
  libsdl2-dev \
  libsdl2-image-dev \
  libsdl2-ttf-dev \
  libsdl2-gfx-dev \
  libboost-all-dev \
  libdirectfb-dev \
  libst-dev \
  glee-dev \
  mesa-utils \
  xvfb \
  x11vnc \
  libsdl-sge-dev \
  python3-pip \
  libboost-all-dev \
  libboost-python-dev \
  tmux

# Install baselines
RUN git clone https://github.com/openai/baselines.git /tmp/baselines
WORKDIR /tmp/baselines
RUN sed -i.bak -e "s@'tf-nightly-gpu'@'tf-nightly-gpu', 'tf-nightly-2.0-preview', 'tf-nightly-gpu-2.0-preview'@" setup.py
RUN python3 setup.py install

WORKDIR /
RUN pip3 install gfootball==1.3
# TODO: Move tensorflow_probability into Dockerfile.grpc
RUN pip3 install tensorflow_probability

# Copy SEED codebase and SEED GRPC library.
ADD . /seed_rl/
WORKDIR /seed_rl
ENTRYPOINT ["python", "gcp/run.py"]
