# Copyright 2019 The SEED Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG grpc_image
FROM $grpc_image

ADD . .

ENTRYPOINT ["bash", "-c", "set -e; for x in `find /seed_rl/grpc/ -name *_test.py`; do PYTHONPATH=/ python3 $x; done"]
