# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc/service.proto',
  package='seed_rl',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12grpc/service.proto\x12\x07seed_rl\"\r\n\x0bInitRequest\";\n\x15MethodOutputSignature\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0coutput_specs\x18\x02 \x01(\x0c\"O\n\x0cInitResponse\x12?\n\x17method_output_signature\x18\x01 \x03(\x0b\x32\x1e.seed_rl.MethodOutputSignature\"/\n\x0b\x43\x61llRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\x12\x0e\n\x06tensor\x18\x02 \x03(\x0c\"Q\n\x0c\x43\x61llResponse\x12\x0e\n\x06tensor\x18\x01 \x03(\x0c\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x1c\n\x14status_error_message\x18\x03 \x01(\t2\x81\x01\n\rTensorService\x12\x35\n\x04Init\x12\x14.seed_rl.InitRequest\x1a\x15.seed_rl.InitResponse\"\x00\x12\x39\n\x04\x43\x61ll\x12\x14.seed_rl.CallRequest\x1a\x15.seed_rl.CallResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='seed_rl.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=44,
)


_METHODOUTPUTSIGNATURE = _descriptor.Descriptor(
  name='MethodOutputSignature',
  full_name='seed_rl.MethodOutputSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='seed_rl.MethodOutputSignature.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_specs', full_name='seed_rl.MethodOutputSignature.output_specs', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=105,
)


_INITRESPONSE = _descriptor.Descriptor(
  name='InitResponse',
  full_name='seed_rl.InitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method_output_signature', full_name='seed_rl.InitResponse.method_output_signature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=186,
)


_CALLREQUEST = _descriptor.Descriptor(
  name='CallRequest',
  full_name='seed_rl.CallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='function', full_name='seed_rl.CallRequest.function', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tensor', full_name='seed_rl.CallRequest.tensor', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=235,
)


_CALLRESPONSE = _descriptor.Descriptor(
  name='CallResponse',
  full_name='seed_rl.CallResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor', full_name='seed_rl.CallResponse.tensor', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='seed_rl.CallResponse.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_error_message', full_name='seed_rl.CallResponse.status_error_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=318,
)

_INITRESPONSE.fields_by_name['method_output_signature'].message_type = _METHODOUTPUTSIGNATURE
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['MethodOutputSignature'] = _METHODOUTPUTSIGNATURE
DESCRIPTOR.message_types_by_name['InitResponse'] = _INITRESPONSE
DESCRIPTOR.message_types_by_name['CallRequest'] = _CALLREQUEST
DESCRIPTOR.message_types_by_name['CallResponse'] = _CALLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'grpc.service_pb2'
  # @@protoc_insertion_point(class_scope:seed_rl.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

MethodOutputSignature = _reflection.GeneratedProtocolMessageType('MethodOutputSignature', (_message.Message,), {
  'DESCRIPTOR' : _METHODOUTPUTSIGNATURE,
  '__module__' : 'grpc.service_pb2'
  # @@protoc_insertion_point(class_scope:seed_rl.MethodOutputSignature)
  })
_sym_db.RegisterMessage(MethodOutputSignature)

InitResponse = _reflection.GeneratedProtocolMessageType('InitResponse', (_message.Message,), {
  'DESCRIPTOR' : _INITRESPONSE,
  '__module__' : 'grpc.service_pb2'
  # @@protoc_insertion_point(class_scope:seed_rl.InitResponse)
  })
_sym_db.RegisterMessage(InitResponse)

CallRequest = _reflection.GeneratedProtocolMessageType('CallRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALLREQUEST,
  '__module__' : 'grpc.service_pb2'
  # @@protoc_insertion_point(class_scope:seed_rl.CallRequest)
  })
_sym_db.RegisterMessage(CallRequest)

CallResponse = _reflection.GeneratedProtocolMessageType('CallResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLRESPONSE,
  '__module__' : 'grpc.service_pb2'
  # @@protoc_insertion_point(class_scope:seed_rl.CallResponse)
  })
_sym_db.RegisterMessage(CallResponse)



_TENSORSERVICE = _descriptor.ServiceDescriptor(
  name='TensorService',
  full_name='seed_rl.TensorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=321,
  serialized_end=450,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='seed_rl.TensorService.Init',
    index=0,
    containing_service=None,
    input_type=_INITREQUEST,
    output_type=_INITRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='seed_rl.TensorService.Call',
    index=1,
    containing_service=None,
    input_type=_CALLREQUEST,
    output_type=_CALLRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TENSORSERVICE)

DESCRIPTOR.services_by_name['TensorService'] = _TENSORSERVICE

# @@protoc_insertion_point(module_scope)
